### ISSUE TITLE
Feature request: more boxes

### ISSUE THREAD

**Issue by ikanakova** [fenimore/badreads#10]
I would be very grateful for more boxes for more information:

- series

- language

- genres / tags

**Comment by fenimore** [comment]
Good idea! Tags are something that i have planned but will probably be later. I can try first series and language

**Comment by fenimore** [comment]
So I've added this in version 0.1.8 (it'll pass review on the play store soon and it'll be up on FDroid too soon once they scan github etc).

If it's not working as expected, please reopen the ticket and let me know.

In case you didn't know, when Editing a book entry, you can select "Fill in missing fields", and Badreads will fetch the Language and Series from Open Library (if available). They'll also show up when you search for new books.
