### ISSUE TITLE
Deleting book crashes the app

### ISSUE THREAD

**Issue by t4k1t** [fenimore/badreads#12]
Version: 0.1.6

Every time I delete a book (in the To Read section at least) the app crashes. As far as I can tell the deletion actually finishes however.

**Comment by fenimore** [comment]
Huh! Thanks for reporting this I'll take a look

**Comment by jeyca** [comment]
I can confirm this behavior

**Comment by fenimore** [comment]
So this should be fixed with version 0.1.8

Please reopen the issue if it doesn't work as expected.

Thank you!
