### ISSUE TITLE
Vertical scan impossible

### ISSUE THREAD

**Issue by Sonegide** [fenimore/badreads#2]
Hello,

Device: Xiaomi Mi 9T Pro
ROM: LineageOS 17

With any app, I have the option, when pivoting my phone, to accept or not the screen to turn horizontally.
With Badreads, this option is not showing. Therefore I cannot scan a vertical barcode.

Thanks

**Comment by fenimore** [comment]
Hey! So I forget which version, but the most recent version should allow you to rotate the phone while scanning :relaxed: lmk if it doesn't work as expected

**Comment by Sonegide** [comment]
Hi,
Sorry for my late reply.
I still have the same issue with the latest version (0.1.5)

**Comment by fenimore** [comment]
Huh :thinking: I think it works as expected for me, I can attach screenshots. Have you selected the auto-rotate option in the drop down menu?
![Screenshot_20210613-202958](https://user-images.githubusercontent.com/10081511/121826646-cce25100-cc86-11eb-8cd3-2384f6e08afe.png)

![Screenshot_20210613-203003](https://user-images.githubusercontent.com/10081511/121826645-cbb12400-cc86-11eb-921d-215ca19e7bf9.png)

**Comment by Sonegide** [comment]
I tried with and without auto-rotate (normally when rotating I have to click on something so the screen also rotate).
Anyway, I have a custom rom, maybe the problem is linked to that.
I will manage without.
Thanks!

**Comment by fenimore** [comment]
Hmm yeah maybe it's a lineage thing 😓 well i could later add some buttons for this screen (eventually i want to add at least a flash button and batch scans). 

For now I'll close the ticket, thanks
