### ISSUE TITLE
Export to CSV does not support special symbols

### ISSUE THREAD

**Issue by DSiekmeier** [fenimore/badreads#26]
I really like the concept of badreads but actually there ist one (for me) serious limitation which prevents using it.

When exporting the library, all special symbols are messed up. This can be tested very easily by adding a book entry with german umlauts (ÄÖÜ). I guess UTF-8 is not used, which in my mind should be the case today.

**Comment by fenimore** [comment]
This is definitely something that should be fixed! Thanks for opening the ticket

**Comment by fenimore** [comment]
I wasn't able to reproduce the issue, when I added an example book (just a random German book I found from the search with an umlaut) Do you have a title/author/character in particular that doesn't work?

![image](https://user-images.githubusercontent.com/10081511/141877433-1deeb39d-e001-432d-a37d-795ae85fe857.png)

**Comment by DSiekmeier** [comment]
It seems that I made the embarrassing mistake not to check the import encoding of the app on my smartphone. It works for me on my desktop pc, too...

Sorry for the circumstances!

**Comment by fenimore** [comment]
I totally understand! Thanks for looking out and opening a ticket anyway 😇
