### ISSUE TITLE
Don't abandon this project

### ISSUE THREAD

**Issue by FinixFighter** [fenimore/badreads#28]
Hi! This post is for saying: please, don't abandon this beautiful piece of software! If the main developer can't work on it anymore then it would be nice if the "goes" to someone else, so that the project can continue to live!
Many thanks!

**Comment by fenimore** [comment]
It's not abandoned, i do spend more time reading then writing code for this application though. That was ultimately my goal, but I'm still here to fix bugs and facilitate contributions

**Comment by FinixFighter** [comment]
Oh that's an amazing news! Sorry for wasting your time with this issue then! :)
