### ISSUE TITLE
Add support for BookWyrm

### ISSUE THREAD

**Issue by LongJohn-Silver** [fenimore/badreads#5]
Basically it would be awesome if this could have any integration at all with [BookWyrm](https://bookwyrm.social/) (a decentralized, libre and privacy respecting project that works with ActivityPub). I know the repo's readme says the idea is to store everything locally, but maybe at some point higher in the development process you decide to go towards another path.

**Comment by fenimore** [comment]
Oh interesting idea! I didn't know about this project, thank you.

**Comment by LongJohn-Silver** [comment]
It's nothing, there is a room in Matrix where the main developer is, if you want to ask some more questions or just chat. This is the address: #bookwyrm:matrix.org

**Comment by LongJohn-Silver** [comment]
Has tere been any thinking if this could be possible, @fenimore?

**Comment by fenimore** [comment]
I checked it out and bookwyrm looks great! It'll be very difficult to integrate these, and I'd have to learn how bookwyrm works on the backend. I love the idea but i don't have any time to go down these rabbit holes atm

**Comment by LongJohn-Silver** [comment]
I understand completely, maybe sometime in the future or if someone else may help you, thanks a lot @fenimore!
