### ISSUE TITLE
Bookmarking

### ISSUE THREAD

**Issue by Aschonberger** [fenimore/badreads#7]
a way of keeping your place in books would be nice, especially for collections of short stories or poetry that are often read intermittently. goodreads does it by page number or percentage, maybe also add section (could be a chapter, poem or story) as an option.

**Comment by fenimore** [comment]
I that is a good idea! I hadn't considered this thank you

**Comment by fenimore** [comment]
Okay @Aschonberger the new release https://github.com/fenimore/badreads/releases/tag/v0.0.7 v0.0.7 (and maybe 0.0.6 :thinking: ) should have a Page number field :relaxed: -- it's pretty simple but I think it fits what you need. Reopen the ticket if it isn't working as expected!
