### ISSUE TITLE
How to install the app?

### ISSUE THREAD

**Issue by PrithirajN** [fenimore/badreads#8]
How can I install the app to my mobile I cannot find the apk file anywhere nor in github or in fdroid?

**Comment by fenimore** [comment]
Oh! That's strange, it ought to be on fdroid. Otherwise there is an APK checked into the source https://github.com/fenimore/badreads/tree/master/app/release

**Comment by PrithirajN** [comment]
I tried but this is showing.
![Screenshot_20210522_003248.jpg](https://user-images.githubusercontent.com/60390549/119186170-57bf9980-ba95-11eb-801d-231a50117137.jpg)

**Comment by PrithirajN** [comment]
And the fdroid page is like this 
![Screenshot_20210522_003504.jpg](https://user-images.githubusercontent.com/60390549/119186362-a3724300-ba95-11eb-97ad-b2ab29fbaa33.jpg)

**Comment by fenimore** [comment]
Huh I'm not sure, but maybe this app requires a higher API version? I wasn't very backwards compatible when making this... What version of Android are you using?

**Comment by PrithirajN** [comment]
8.1

**Comment by fenimore** [comment]
Huh, it might work then, that's API level 27, if it's not compatible it probably isn't hard getting it to be

**Comment by fenimore** [comment]
Ya unfortunately versión 29 is the lowest, i can try to make it compatible with more devices though it would be nice

**Comment by PrithirajN** [comment]
That would be get.

**Comment by fenimore** [comment]
Hey! So you can try this release: https://github.com/fenimore/badreads/releases/tag/v0.1.0 which will be available in FDroid Soon,

**Comment by PrithirajN** [comment]
Yes the app got installed but it gave the play protect warning.

**Comment by fenimore** [comment]
Okay, if you are worried about play protect, you could wait for the official playstore release or maybe the f droid release. I'm glad it's now compatible!

I'll try to continue lowering the minimum SDK (it's at 27 now but I think it can be lower).

**Comment by fenimore** [comment]
https://play.google.com/store/apps/details?id=com.timenotclocks.bookcase&hl=en_US&gl=US
