### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by githubIsNotOpenSourceLOL** [fenimore/badreads#9]
I was looking for a FOSS alternative for Goodreads for a long time! Thanks for your work!
Is there a way to donate to the project?

**Comment by fenimore** [comment]
Hi! I'm happy to hear this! Thank you very much for your kind words, it means a lot that other people find this software useful, even if it only offers a fraction of what goodreads offers, it suffices for me and as you see it's FOSS, which is important to me too!

I hope you continue to find the app useful, and let me know if there are ways to improve or fix it!

As for donations, I haven't really thought it through, and unfortunately the only way to donate is with proprietary software 😒, which would be with Venmo. But nevertheless! I do like donations! So you can find me on venmo `@fenfund`, name Fen L

Thanks again for the encouragement and kind words! I appreciate it very much

**Comment by githubIsNotOpenSourceLOL** [comment]
Do you also have Paypal? It would be nice, if you just include a donation link to PayPal in the README :)

**Comment by fenimore** [comment]
Hi! Good idea! 

Thanks again :flushed: I really appreciate the support! 

I'll close the ticket now that I added a link in the readme with a little note - if it doesn't work let me know and reopen I'll take a look :relaxed:

**Comment by fenimore** [comment]
Oh just to be clear here is the subheading: https://github.com/fenimore/badreads/#support-badreads

Also on Paypal its `@timenotclocks` (Also venmo is too now)

https://www.paypal.com/paypalme/timenotclocks
